//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5.Componens
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDish
    {
        public int OrserId { get; set; }
        public int DishId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
    }
}
