//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiterWpf.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookingStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CookingStage()
        {
            this.IngredientOfCookingSage = new HashSet<IngredientOfCookingSage>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> DishId { get; set; }
        public string TimeintMinutes { get; set; }
    
        public virtual Dish Dish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientOfCookingSage> IngredientOfCookingSage { get; set; }
    }
}
