//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWpf.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Landing
    {
        public int IngredientId { get; set; }
        public int ProviderId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
